#!/usr/bin/env bash
# uses scp to copy files from client to server
if [ "$#" -lt 4 ];
then
    echo Usage: 0-transfer_file PATH_TO_FILE IPSERNAME PATH_TO_SSH_KEY
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi
