#!/usr/bin/env bash
# clock function
hr=0
min=1

while [ $hr -lt 13 ]
do
    echo "Hour: $hr"
    while [ $hr -lt 13 ] && [ $min -lt 60 ]
    do
	echo "$min"
	: $(( min++ ))
    done
    min=1
    : $(( hr++ ))
done
